apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-apiserver
  namespace: tenant-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kube-apiserver
      tenant: tenant-1
  template:
    metadata:
      labels:
        app: kube-apiserver
        tenant: tenant-1
    spec:
      containers:
      - name: apiserver
        image: k8s.gcr.io/kube-apiserver:v1.23.4
        command:
        - kube-apiserver
        - --advertise-address=0.0.0.0
        - --allow-privileged=true
        - --authorization-mode=Node,RBAC
        - --client-ca-file=/etc/kubernetes/pki/server/ca.crt
        - --enable-admission-plugins=NodeRestriction
        - --enable-bootstrap-token-auth=true
        - --etcd-cafile=/etc/kubernetes/pki/etcd/ca.crt
        - --etcd-certfile=/etc/kubernetes/pki/etcd/apiserver-etcd-client.crt
        - --etcd-keyfile=/etc/kubernetes/pki/etcd/apiserver-etcd-client.key
        - --etcd-servers=https://172.18.0.2:2379
        - --etcd-prefix=/tenant-1/registry
        - --insecure-port=0
        - --kubelet-client-certificate=/etc/kubernetes/pki/server/apiserver-kubelet-client.crt
        - --kubelet-client-key=/etc/kubernetes/pki/server/apiserver-kubelet-client.key
        - --kubelet-preferred-address-types=InternalIP,ExternalIP,Hostname
        - --proxy-client-cert-file=/etc/kubernetes/pki/server/front-proxy-client.crt
        - --proxy-client-key-file=/etc/kubernetes/pki/server/front-proxy-client.key
        - --requestheader-allowed-names=front-proxy-client
        - --requestheader-client-ca-file=/etc/kubernetes/pki/server/front-proxy-ca.crt
        - --requestheader-extra-headers-prefix=X-Remote-Extra-
        - --requestheader-group-headers=X-Remote-Group
        - --requestheader-username-headers=X-Remote-User
        - --secure-port=6443
        - --service-account-issuer=https://kubernetes.default.svc.cluster.local
        - --service-account-key-file=/etc/kubernetes/pki/server/sa.pub
        - --service-account-signing-key-file=/etc/kubernetes/pki/server/sa.key
        - --service-cluster-ip-range=10.101.0.0/16
        - --tls-cert-file=/etc/kubernetes/pki/server/apiserver.crt
        - --tls-private-key-file=/etc/kubernetes/pki/server/apiserver.key
        volumeMounts:
        - name: etcd-cert
          mountPath: /etc/kubernetes/pki/etcd
          readOnly: true
        - name: server-cert
          mountPath: /etc/kubernetes/pki/server
          readOnly: true
        livenessProbe:
          failureThreshold: 8
          httpGet:
            host: 127.0.0.1
            path: /livez
            port: 6443
            scheme: HTTPS
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 15
        readinessProbe:
          failureThreshold: 3
          httpGet:
            host: 127.0.0.1
            path: /readyz
            port: 6443
            scheme: HTTPS
          periodSeconds: 1
          successThreshold: 1
          timeoutSeconds: 15
        startupProbe:
          failureThreshold: 24
          httpGet:
            host: 127.0.0.1
            path: /livez
            port: 6443
            scheme: HTTPS
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 15
      volumes:
      - name: etcd-cert
        secret:
          secretName: etcd-cert
      - name: server-cert
        secret:
          secretName: server-cert
---
apiVersion: v1
kind: Service
metadata:
  name: kube-apiserver
  namespace: tenant-1
spec:
  selector:
    app: kube-apiserver
    tenant: tenant-1
  ports:
  - name: https
    protocol: TCP
    port: 6443
    targetPort: 6443
