apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: tenant-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
      tenant: tenant-1
  template:
    metadata:
      labels:
        app: nginx
        tenant: tenant-1
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        volumeMounts:
        - name: etcd-cert
          mountPath: /etcd/kubernetes/pki/etcd
          readOnly: true
        - name: server-cert
          mountPath: /etc/kubernetes/pki/server
          readOnly: true
      volumes:
      - name: etcd-cert
        secret:
          secretName: etcd-cert
      - name: server-cert
        secret:
          secretName: server-cert
