apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: multi-tenants-manager
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: multi-tenants-manager
subjects:
  - kind: ServiceAccount
    name: multi-tenants-manager
    namespace: default
